import { expect, test } from '@playwright/test'

test('seeded demo stocks workflow', async ({ page }) => {
  await page.addInitScript(() => {
    window.localStorage.setItem('locale', 'en')
  })
  await page.goto('/stocks')
  await expect(page).toHaveURL(/\/login\?redirect=\/stocks/)

  await page.locator('#login-email').fill('demo@example.com')
  await page.locator('#login-password').fill('demo1234')
  await page.getByRole('button', { name: /sign in/i }).click()

  await expect(page).toHaveURL(/\/stocks/)
  await expect(page.getByRole('heading', { name: 'Portfolio Holdings' })).toBeVisible()
  await expect(page.locator('.portfolio-currency-section').filter({ hasText: 'TWD' })).toContainText('NT$')
  await expect(page.locator('.portfolio-currency-section').filter({ hasText: 'USD' })).toContainText('US$')
  await expect(page.getByRole('heading', { name: 'Trade History' })).toBeVisible()
  await expect(page.locator('.watchlist-tile').filter({ hasText: 'Profitable US sale' })).toBeVisible()
  await expect(page.locator('.trade-summary-panel').filter({ hasText: 'TWD' })).toContainText('NT$')
  await expect(page.locator('.trade-summary-panel').filter({ hasText: 'USD' })).toContainText('US$')

  const initialE2eHoldingCount = await page.locator('.portfolio-position-card').filter({ hasText: 'ZZZE2E' }).count()
  expect(initialE2eHoldingCount).toBe(0)

  await page.locator('#trade-stock-code').fill('ZZZE2E')
  await page.locator('#trade-type').selectOption('BUY')
  await page.locator('#trade-date').fill('2026-07-20')
  await page.locator('#trade-shares').fill('10')
  await page.locator('#trade-price').fill('20')
  await page.locator('#trade-fee').fill('1')
  await page.locator('#trade-tax').fill('0')
  await page.locator('#trade-note').fill('E2E deterministic buy')
  await page.getByRole('button', { name: 'Create Trade' }).click()
  await expect(page.getByText('Trade created.')).toBeVisible()
  await expect(page.locator('.portfolio-position-card').filter({ hasText: 'ZZZE2E' })).toContainText('10')

  await page.locator('#trade-stock-code').fill('ZZZE2E')
  await page.locator('#trade-type').selectOption('SELL')
  await page.locator('#trade-date').fill('2026-07-21')
  await page.locator('#trade-shares').fill('4')
  await page.locator('#trade-price').fill('25')
  await page.locator('#trade-fee').fill('1')
  await page.locator('#trade-tax').fill('0')
  await page.locator('#trade-note').fill('E2E deterministic sell')
  await page.getByRole('button', { name: 'Create Trade' }).click()
  await expect(page.getByText('Trade created.')).toBeVisible()
  await expect(page.locator('.portfolio-position-card').filter({ hasText: 'ZZZE2E' })).toContainText('6')
  await expect(page.locator('.trade-summary-panel').filter({ hasText: 'USD' })).toContainText('Gross Proceeds')

  await page.locator('#trade-stock-code').fill('ZZZE2E')
  await page.locator('#trade-type').selectOption('SELL')
  await page.locator('#trade-date').fill('2026-07-22')
  await page.locator('#trade-shares').fill('99')
  await page.locator('#trade-price').fill('25')
  await page.locator('#trade-fee').fill('0')
  await page.locator('#trade-tax').fill('0')
  await page.locator('#trade-note').fill('E2E oversell')
  await page.getByRole('button', { name: 'Create Trade' }).click()
  await expect(page.getByText(/negative inventory/i).first()).toBeVisible()

  page.once('dialog', async (dialog) => {
    expect(dialog.message()).toContain('recalculate all later FIFO results')
    await dialog.accept()
  })
  await page.locator('.watchlist-tile').filter({ hasText: 'E2E deterministic sell' }).getByRole('button', { name: 'Delete' }).click()
  await expect(page.getByText('Trade deleted.')).toBeVisible()
  await expect(page.locator('.portfolio-position-card').filter({ hasText: 'ZZZE2E' })).toContainText('10')

  page.once('dialog', async (dialog) => {
    await dialog.accept()
  })
  await page.locator('.watchlist-tile').filter({ hasText: 'E2E deterministic buy' }).getByRole('button', { name: 'Delete' }).click()
  await expect(page.getByText('Trade deleted.')).toBeVisible()
  await expect(page.locator('.portfolio-position-card').filter({ hasText: 'ZZZE2E' })).toHaveCount(0)

  await page.locator('#holding-stock-code').fill('MSFT')
  await page.locator('#holding-shares').fill('1')
  await page.locator('#holding-average-cost').fill('300')
  await page.locator('#holding-note').fill('E2E missing price')
  await page.getByRole('button', { name: 'Add Holding' }).click()
  await expect(page.getByText('Holding saved.')).toBeVisible()
  await expect(page.getByText('Latest price unavailable for MSFT.')).toBeVisible()
  await expect(page.getByText('Partial prices')).toBeVisible()
  await expect(page.getByText('Priced Market Value')).toBeVisible()
  await expect(page.getByText('Unpriced Cost')).toBeVisible()

  const msftCard = page.locator('.portfolio-position-card').filter({ hasText: 'MSFT' })
  await msftCard.getByRole('button', { name: 'Edit' }).click()
  await page.locator('#holding-shares').fill('2')
  await page.getByRole('button', { name: 'Update Holding' }).click()
  await expect(page.getByText('Holding updated.')).toBeVisible()
  await expect(msftCard).toContainText('2')

  await msftCard.getByRole('button', { name: 'Delete' }).click()
  await expect(page.getByText('Holding deleted.')).toBeVisible()
  await expect(page.locator('.portfolio-position-card').filter({ hasText: 'MSFT' })).toHaveCount(0)

  await page.getByRole('button', { name: 'Sign Out' }).click()
  await expect(page).toHaveURL(/\/login/)
  await page.goto('/stocks')
  await expect(page).toHaveURL(/\/login\?redirect=\/stocks/)
})
